# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 939f33f422e5b3130600d2de2b442e222110e27bdc0cd66f936da3be188eeb3151c7dfbd4cb8419dab70b9cb0a6c0bcfb17973d8e17b3370c4150111c487efa4

test:
  secret_key_base: 66271762bfeefad0642a94f6d704591564fddcfc6206aa3c3a8395b12acf8d94f4123451f45f40131763fb16e3019a001da67fe890e40a0517660efd51eee827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
